import asyncio
import json
import logging
import sys
import uuid
from pathlib import Path
from typing import Any, Optional
from fastapi import APIRouter, Depends, HTTPException, WebSocket

# Ensure src/agents/ is on sys.path for tradingagents imports
_agents_dir = Path(__file__).resolve().parent.parent.parent / "agents"
if str(_agents_dir) not in sys.path:
    sys.path.insert(0, str(_agents_dir))

from src.api.dependencies import get_services, AppServices
from src.api.models import (
    AnalysisFeedbackRequest, AnalysisFeedbackResponse, AnalysisFeedbackItem,
    AnalysisJobListItem, AnalysisRequest, AnalysisStatusResponse, AnalysisStepItem,
)
from src.agents.tradingagents.agents.analyst_registry import AnalystRegistry
from src.orchestrator.state import AnalysisJob

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/analysis", tags=["analysis"])


def _load_flow_log(log_path: Path) -> Any:
    """Load the full_states_log JSON file (sync, meant for thread pool)."""
    if not log_path.exists():
        return None
    with open(log_path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def _normalize_status(status: str) -> str:
    return "completed" if status == "done" else status


def _job_to_response(job) -> AnalysisStatusResponse:
    return AnalysisStatusResponse(
        job_id=job.id,
        symbol=job.symbol,
        status=_normalize_status(job.status.value),
        phase=job.phase,
        progress=job.progress,
        result_summary=job.result_summary or "",
        error=job.error or "",
        steps=[
            AnalysisStepItem(
                step_id=s.step_id,
                label=s.label,
                role=s.role,
                character=s.character,
                module=s.module,
                action=s.action,
                artifact_key=s.artifact_key,
                status=s.status.value,
                started_at=s.started_at.isoformat() if s.started_at else None,
                completed_at=s.completed_at.isoformat() if s.completed_at else None,
                detail=s.detail,
            )
            for s in job.steps
        ],
        created_at=job.created_at.isoformat() if job.created_at else None,
        output_files=job.output_files,
    )


@router.post("/")
async def start_analysis(body: AnalysisRequest, services: AppServices = Depends(get_services)):
    """Create a pending analysis job. The actual execution is handled by the background worker."""
    config = {}
    if body.output_language:
        config["output_language"] = body.output_language
    if body.llm_provider:
        config["llm_provider"] = body.llm_provider
    if body.analysts:
        config["analysts"] = body.analysts
    if body.research_depth:
        config["research_depth"] = body.research_depth
    if body.thinking_agents is not None:
        config["thinking_agents"] = body.thinking_agents
    if body.trade_date:
        config["trade_date"] = body.trade_date
    if body.checkpoint_enabled is not None:
        config["checkpoint_enabled"] = body.checkpoint_enabled

    job = AnalysisJob(
        id=str(uuid.uuid4())[:8],
        symbol=body.symbol,
        config=config if config else None,
    )
    await services.job_store.save(job)
    return _job_to_response(job)


@router.get("/jobs", response_model=list[AnalysisJobListItem])
async def list_jobs(
    symbol: Optional[str] = None,
    status: Optional[str] = None,
    limit: int = 50,
    services: AppServices = Depends(get_services),
):
    """List historical analysis jobs with optional filters. Slim response for list view."""
    jobs = await services.job_store.list_jobs(
        symbol=symbol,
        status=status,
        limit=limit,
        summary_only=True,
    )
    return [
        AnalysisJobListItem(
            job_id=j.id,
            symbol=j.symbol,
            status=_normalize_status(j.status.value),
            progress=j.progress,
            created_at=j.created_at.isoformat() if j.created_at else None,
        )
        for j in jobs
    ]


@router.get("/{job_id}/status", response_model=AnalysisStatusResponse)
async def get_status(job_id: str, services: AppServices = Depends(get_services)):
    job = await services.job_store.get(job_id)
    if not job:
        return AnalysisStatusResponse(
            job_id=job_id, symbol="", status="not_found", progress="",
        )
    return _job_to_response(job)


@router.get("/{job_id}/files")
async def get_job_files(job_id: str, services: AppServices = Depends(get_services)):
    """Return output file paths generated by this analysis job."""
    files = await services.job_store.get_output_files(job_id)
    return {"job_id": job_id, "files": files}


@router.get("/{job_id}/flow")
async def get_analysis_flow(job_id: str, services: AppServices = Depends(get_services)):
    """Parse the full_states_log for this job and return a structured pipeline flow."""
    job = await services.job_store.get(job_id)
    if not job:
        return {"error": "Job not found", "steps": []}

    log_path: Path | None = None
    for f in job.output_files:
        if "full_states_log" in f and f.endswith(".json"):
            log_path = Path(f)
            break

    if not log_path:
        return {"steps": []}

    try:
        # Offload sync file I/O to thread so the event loop stays responsive
        loop = asyncio.get_event_loop()
        state = await loop.run_in_executor(None, _load_flow_log, log_path)
        if state is None:
            return {"steps": []}
    except Exception:
        return {"steps": []}

    steps: list[dict] = []

    steps.append({
        "name": "数据采集",
        "status": "done",
        "summary": f"股票: {state.get('company_of_interest', '')}, 日期: {state.get('trade_date', '')}",
    })

    reg = AnalystRegistry()
    analyst_map = [(e.report_key, e.label) for e in reg.list()]
    analyst_map.append(("data_quality_summary", "数据质量评估"))

    for key, label in analyst_map:
        content = state.get(key, "")
        if content:
            steps.append({
                "name": label,
                "status": "done",
                "summary": content[:300] + ("..." if len(content) > 300 else ""),
            })

    inv_debate = state.get("investment_debate_state", {})
    if inv_debate.get("judge_decision"):
        steps.append({
            "name": "多空辩论",
            "status": "done",
            "summary": inv_debate["judge_decision"][:300],
        })

    risk_debate = state.get("risk_debate_state", {})
    if risk_debate.get("judge_decision"):
        steps.append({
            "name": "风险评估",
            "status": "done",
            "summary": risk_debate["judge_decision"][:300],
        })

    plan = state.get("investment_plan", "") or state.get("trader_investment_plan", "")
    if plan:
        steps.append({
            "name": "交易计划",
            "status": "done",
            "summary": plan[:300] + ("..." if len(plan) > 300 else ""),
        })

    decision = state.get("final_trade_decision", "")
    if decision:
        steps.append({
            "name": "最终决策",
            "status": "done",
            "summary": decision[:300] + ("..." if len(decision) > 300 else ""),
        })

    return {"steps": steps}


@router.post("/{job_id}/feedback")
async def post_feedback(
    job_id: str,
    body: AnalysisFeedbackRequest,
    services: AppServices = Depends(get_services),
):
    """Submit feedback (upvote/downvote) for a specific analysis step."""
    job = await services.job_store.get(job_id)
    if not job:
        return {"error": "Job not found"}

    await services.job_store.save_feedback(
        job_id=job_id,
        step_id=body.step_id,
        feedback_type=body.feedback_type,
        comment=body.comment,
    )
    return {"success": True}


@router.get("/{job_id}/feedback", response_model=AnalysisFeedbackResponse)
async def get_feedback(job_id: str, services: AppServices = Depends(get_services)):
    """Get all feedback for a job, including summary."""
    job = await services.job_store.get(job_id)
    if not job:
        return AnalysisFeedbackResponse(job_id=job_id, feedbacks=[], summary={"upvotes": 0, "downvotes": 0})

    feedbacks = await services.job_store.get_feedback(job_id)
    summary = await services.job_store.get_feedback_summary(job_id)
    return AnalysisFeedbackResponse(
        job_id=job_id,
        feedbacks=[
            AnalysisFeedbackItem(
                step_id=f["step_id"],
                feedback_type=f["feedback_type"],
                comment=f["comment"],
                created_at=f["created_at"],
            )
            for f in feedbacks
        ],
        summary=summary,
    )


@router.post("/{job_id}/retry")
async def retry_job(job_id: str, services: AppServices = Depends(get_services)):
    """Manually retry a failed analysis job."""
    job = await services.job_store.get(job_id)
    if not job or job.status.value != "error":
        raise HTTPException(status_code=400, detail="任务不存在或不在错误状态")
    job.retry()
    await services.job_store.save(job)
    return _job_to_response(job)


@router.websocket("/{symbol}/stream")
async def analysis_stream(websocket: WebSocket, symbol: str, services: AppServices = Depends(get_services)):
    await websocket.accept()
    job = AnalysisJob(id=str(uuid.uuid4())[:8], symbol=symbol)
    await services.job_store.save(job)

    while job.status.value in ("pending", "running"):
        await websocket.send_json({
            "job_id": job.id,
            "status": job.status.value,
            "progress": job.progress,
        })
        await asyncio.sleep(1)
        # Re-fetch from store if updated elsewhere
        stored = await services.job_store.get(job.id)
        if stored:
            job.status = stored.status
            job.progress = stored.progress

    # Send final
    await websocket.send_json({
        "job_id": job.id,
        "status": _normalize_status(job.status.value),
        "progress": job.progress,
        "result_summary": job.result_summary or "",
    })
    await websocket.close()
